/** Short player guide per unit: what it is and what it's mostly used for (classic Travian play). */
export const UNIT_GUIDE: Record<string, { kind: string; use: string }> = {
  // Romans
  legionnaire: { kind: 'Balanced infantry', use: 'All-rounder for early raids and village defence; cheap backbone of a young Roman army.' },
  praetorian: { kind: 'Defensive infantry', use: 'Best Roman defence against infantry attacks; keep at home or send as reinforcement.' },
  imperian: { kind: 'Offensive infantry', use: 'Main Roman attacker: strong, cheap attack per crop — the core of a hammer army.' },
  equites_legati: { kind: 'Scout (cavalry)', use: 'Spies on enemy troops and resources before you attack; also defends against enemy scouts.' },
  equites_imperatoris: { kind: 'Offensive cavalry', use: 'Fast, strong raider and attacker; great for farming resources from inactive villages.' },
  equites_caesaris: { kind: 'Heavy cavalry', use: 'Strong attack and the best Roman defence against cavalry; slow but very powerful.' },
  battering_ram: { kind: 'Siege (ram)', use: 'Knocks down the enemy wall so your attack faces less defence. Send with a normal attack.' },
  fire_catapult: { kind: 'Siege (catapult)', use: 'Destroys enemy buildings and fields; aim it at warehouses, granaries or the Residence/Palace before conquering.' },
  senator: { kind: 'Administrator', use: 'Lowers a village’s loyalty (20–30% per attack) to conquer it. Needs culture points and a free expansion slot.' },
  roman_settler: { kind: 'Settler', use: 'Three settlers found a new village on an empty field.' },
  // Teutons
  clubswinger: { kind: 'Cheap offensive infantry', use: 'Fastest and cheapest to train; raid neighbours early and build a big hammer cheaply.' },
  spearman: { kind: 'Defensive infantry', use: 'Cheap defence, especially good against cavalry.' },
  axeman: { kind: 'Offensive infantry', use: 'The Teutons’ strongest infantry attacker; core of late-game hammers.' },
  scout: { kind: 'Scout (infantry)', use: 'Spies on enemy villages; trained in the barracks. Also defends against enemy scouts.' },
  paladin: { kind: 'Defensive cavalry', use: 'Mobile defender that can rush to help allies; decent against infantry.' },
  teutonic_knight: { kind: 'Offensive cavalry', use: 'Powerful cavalry attacker and raider with good carrying capacity.' },
  ram: { kind: 'Siege (ram)', use: 'Destroys the enemy wall during a normal attack.' },
  catapult: { kind: 'Siege (catapult)', use: 'Destroys buildings and fields; needed to remove a Residence/Palace before conquering.' },
  chief: { kind: 'Administrator', use: 'Lowers a village’s loyalty (20–25% per attack) to conquer it.' },
  teuton_settler: { kind: 'Settler', use: 'Three settlers found a new village on an empty field.' },
  // Gauls
  phalanx: { kind: 'Defensive infantry', use: 'Cheap all-round defender; the Gaul’s main village guard.' },
  swordsman: { kind: 'Offensive infantry', use: 'Solid infantry attacker that can also defend against cavalry.' },
  pathfinder: { kind: 'Scout (cavalry)', use: 'Fast spy for scouting enemies and defending against enemy scouts.' },
  theutates_thunder: { kind: 'Fast raiding cavalry', use: 'The fastest unit in the game: perfect raider and quick strike force.' },
  druidrider: { kind: 'Defensive cavalry', use: 'Strong defence against infantry; fast enough to reinforce allies quickly.' },
  haeduan: { kind: 'Heavy cavalry', use: 'Strong attacker and defender against cavalry; the Gaul’s elite unit.' },
  gaul_ram: { kind: 'Siege (ram)', use: 'Destroys the enemy wall during a normal attack.' },
  trebuchet: { kind: 'Siege (catapult)', use: 'Destroys buildings and fields; aim it at what you want gone.' },
  chieftain: { kind: 'Administrator', use: 'Lowers a village’s loyalty (20–25% per attack) to conquer it.' },
  gaul_settler: { kind: 'Settler', use: 'Three settlers found a new village on an empty field.' },
  // Nature
  rat: { kind: 'Animal', use: 'The weakest oasis animal; easy hero experience.' },
  spider: { kind: 'Animal', use: 'Weak oasis guard.' },
  snake: { kind: 'Animal', use: 'Oasis guard with fair attack.' },
  bat: { kind: 'Animal', use: 'Oasis guard; stronger than it looks.' },
  boar: { kind: 'Animal', use: 'Sturdy oasis guard with good defence against infantry.' },
  wolf: { kind: 'Animal', use: 'Strong oasis guard; bring a real army.' },
  bear: { kind: 'Animal', use: 'Very strong oasis guard, especially against cavalry.' },
  crocodile: { kind: 'Animal', use: 'One of the toughest oasis guards; great hero experience.' },
  tiger: { kind: 'Animal', use: 'Dangerous oasis guard, strong against cavalry.' },
  elephant: { kind: 'Animal', use: 'The mightiest oasis animal; huge experience for your hero.' },
  // Natars
  pikeman: { kind: 'Natar infantry', use: 'Natar defender guarding artifacts and World Wonders.' },
  thorned_warrior: { kind: 'Natar infantry', use: 'Natar fighter guarding artifacts and World Wonders.' },
  guardsman: { kind: 'Natar heavy infantry', use: 'Elite Natar defender — expect heavy losses attacking it.' },
  birds_of_prey: { kind: 'Natar scout', use: 'Natar scout.' },
  axerider: { kind: 'Natar cavalry', use: 'Natar cavalry guarding their strongholds.' },
  natarian_knight: { kind: 'Natar heavy cavalry', use: 'Elite Natar cavalry.' },
  war_elephant: { kind: 'Natar siege', use: 'Natar siege beast.' },
  ballista: { kind: 'Natar siege', use: 'Natar siege engine.' },
  natarian_emperor: { kind: 'Natar ruler', use: 'Leader of the Natars.' },
  natar_settler: { kind: 'Natar settler', use: 'Natar colonist.' },
};
